image: node:latest

pipelines:
  branches:
    development:
      - step:
          name: Build and Deploy to QA
          deployment: qa
          script:
            - npm install -g @angular/cli 
            - npm install 
            - export NODE_OPTIONS="--max-old-space-size=4096"
            - ng build --configuration=dev --no-strict || true 
            - echo "$AWS_EC2_QA" | base64 --decode > /tmp/qa_key.pem  
            - chmod 600 /tmp/qa_key.pem  
            - scp -i /tmp/qa_key.pem -r dist/main ec2-user@ec2-52-87-171-214.compute-1.amazonaws.com:~/ 
