image: node:latest

pipelines:
  branches:
    development:
      - step:
          name: Build and Deploy to QA
          deployment: qa
          script:
            - npm install -g @angular/cli
            - npm install
            - export NODE_OPTIONS="--max-old-space-size=4096"
            - ng build --configuration=dev || true
            - ls -ltr
            - cd dist/main
            - pipe: atlassian/aws-s3-deploy:1.0.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: 'us-east-1'
                S3_BUCKET: 'hero-deploy'
                LOCAL_PATH: 'dist/main/'
                S3_PATH: 'deployments/qa/'
                EXTRA_ARGS: '--acl public-read'
    master:
      - step:
          name: Build and Deploy to Production
          deployment: production
          script:
            - npm install -g @angular/cli
            - npm install
            - export NODE_OPTIONS="--max-old-space-size=4096"
            - ng build --configuration=production || true
            - ls -ltr
            - cd dist/main
            - pipe: atlassian/aws-s3-deploy:1.0.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: 'us-east-1'
                S3_BUCKET: 'hero-deploy'
                LOCAL_PATH: 'dist/main/'
                S3_PATH: 'deployments/prod/'
                EXTRA_ARGS: '--acl public-read'
