image: node:latest

pipelines:
  branches:
    development:
      - step:
          name: Build and Deploy to QA
          deployment: qa
          script:
            - npm install -g @angular/cli
            - npm install
            - export NODE_OPTIONS="--max-old-space-size=4096"
            - ng build --configuration=dev || true
            - echo "$AWS_EC2_QA" > /tmp/qa_key.pem
            - chmod 600 /tmp/qa_key.pem
            - mkdir -p ~/.ssh
            - ssh-keyscan ec2-52-87-171-214.compute-1.amazonaws.com >> ~/.ssh/known_hosts
            - ssh -o StrictHostKeyChecking=no -i /tmp/qa_key.pem ec2-user@ec2-52-87-171-214.compute-1.amazonaws.com echo "SSH connection successful"
            - scp -o StrictHostKeyChecking=no -i /tmp/qa_key.pem -r dist/main ec2-user@ec2-52-87-171-214.compute-1.amazonaws.com:~/
    master:
      - step:
          name: Build and Deploy to Production
          deployment: production
          script:
            - npm install -g @angular/cli
            - npm install
            - export NODE_OPTIONS="--max-old-space-size=4096"
            - ng build --configuration=production || true
            - echo "$AWS_EC2_PROD" > /tmp/prod_key.pem
            - chmod 600 /tmp/prod_key.pem
            - mkdir -p ~/.ssh
            - ssh-keyscan ec2-34-201-84-100.compute-1.amazonaws.com >> ~/.ssh/known_hosts
            - ssh -o StrictHostKeyChecking=no -i /tmp/prod_key.pem ec2-user@ec2-54-210-34-211.compute-1.amazonaws.com echo "SSH connection successful"
            - scp -o StrictHostKeyChecking=no -i /tmp/prod_key.pem -r dist/main ec2-user@ec2-54-210-34-211.compute-1.amazonaws.com:~/
