import { RouteInfo } from './sidebar.metadata';
export const ROUTES: RouteInfo[] = [
  {
    path: '',
    title: 'MENUITEMS.MAIN.TEXT',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '/app/home',
    title: 'MENUITEMS.HOME.TEXT',
    iconType: 'feather',
    icon: 'home',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '',
    title: 'MENUITEMS.BILLING.TEXT',
    iconType: 'feather',
    icon: 'file',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [
      {
        path: '/app/billing-purchase',
        title: 'MENUITEMS.BILLING-PURCHASE.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: '/app/billing-purchases',
        title: 'MENUITEMS.BILLING-MY-PURCHASES.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: '/app/academy',
        title: 'Adquirir Academia Trading',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: '/app/funding-account',
        title: 'Adquirir Cuenta de fondeo',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
    ],
  },
  {
    path: '/app/network',
    title: 'MENUITEMS.NETWORK.TEXT',
    iconType: 'feather',
    icon: 'rss',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
  },
  {
    path: '',
    title: 'MENUITEMS.WALLET.TEXT',
    iconType: 'feather',
    icon: 'credit-card',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [
      {
        path: '/app/wallet',
        title: 'WALLET-PAGE.SUBMENU-TITLE.TEXT',
        iconType: 'feather',
        icon: 'credit-card',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      {
        path: '/app/requests',
        title: 'MENUITEMS.REQUEST-PAY.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        submenu: [],
      },
      // {
      //   path: '/app/request-wallet',
      //   title: 'MENUITEMS.REQUEST-WALLET.TEXT',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   submenu: [],
      // },
      // {
      //   path: '/app/commissions',
      //   title: 'MENUITEMS.MY-COMMISSIONS.TEXT',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   submenu: [],
      // },
      // {
      //   path: '/app/commissions-balance',
      //   title: 'MENUITEMS.COMMISSIONS-BALANCE.TEXT',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   submenu: [],
      // },
    ],
  },


  // {
  //   path: '/app/addresses',
  //   title: 'MENUITEMS.ADDRESSES.TEXT',
  //   iconType: 'feather',
  //   icon: 'map-pin',
  //   class: '',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   submenu: [],
  // },
  // {
  //   path: '',
  //   title: 'MENUITEMS.TOOLS.TEXT',
  //   iconType: 'feather',
  //   icon: 'tag',
  //   class: 'menu-toggle',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   submenu: [
  //     {
  //       path: '/app/tickets',
  //       title: 'MENUITEMS.MY-TICKETS.TEXT',
  //       iconType: 'feather',
  //       icon: 'book-open',
  //       class: '',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       submenu: [],
  //     },
  //     {
  //       path: '/app/news',
  //       title: 'MENUITEMS.NEWS.TEXT',
  //       iconType: 'feather',
  //       icon: 'book-open',
  //       class: '',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       submenu: [],
  //     },
  //   ],

  // },


];
